#!/usr/bin/env python
import gitmagic
from git import Repo
from git.cmd import Git

def simple_change_finder(repo):
    for diff in repo.head.commit.diff(None):
        yield gitmagic.Change(diff.a_path, diff.b_path, "", "", (), (), "")

repo = Repo('.')
c_range = gitmagic.commit_range(repo)
destination_picker = gitmagic.FixupDestinationPicker(repo, c_range)
gitmagic.fixup(repo, destination_picker, simple_change_finder)
git = Git(repo.working_dir)
git.execute(['git', '-c', 'core.editor=/bin/true', 'rebase', '--autosquash', '-i', 'master' ])
