#!/usr/bin/env python
import gitmagic
from git import Repo


repo = Repo('.')
initial_commit = "f445741336ae7e4e6de585ffdc3807e120339b46"
common_ancestor = repo.merge_base(initial_commit, 'HEAD')
commit_range = []

for commit in repo.iter_commits(None):
    if commit == common_ancestor:
        break
    commit_range.append(commit)

changes = gitmagic.find_changes(repo)
commit_picker = gitmagic.FixupDestinationPicker(repo, commit_range)
for change in changes:
    print( "{} -> {}".format(change, commit_picker.pick(change)))

